name: haulistry
description: A booking platform for heavy machinery and transport services
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  get: ^4.6.6
  
  # Navigation
  go_router: ^16.2.4
  
  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
  # Date & Time
  intl: ^0.20.2
  
  # Networking
  http: ^1.2.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Image Picker
  image_picker: ^1.0.7
  
  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.5.3
  
  # Animations
  lottie: ^3.0.0
  flutter_animate: ^4.5.0
  
  # Icons
  font_awesome_flutter: ^10.7.0
  
  # Rating
  flutter_rating_bar: ^4.0.1
  
  # URL Launcher
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Uncomment and add specific assets as needed
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  
  # Custom fonts can be added here when needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont.ttf
